### ISSUE TITLE
Feature suggestion - "None" filter

### ISSUE THREAD

**Issue by PurpleMonkeyDishwasher77** [emfmesquita/master-strike#20]
Hello, I recently found master-strike.com and love it!  Can you please consider adding a "None" filter criteria to the Heroes -> Keyword and Heroes -> Extra Rules filters?  I'm still learning the game and branching out beyond the core set, I'd like to start crafting hero combinations and I'd like the ability to see a list of Heroes that include specific keywords that I've learned (e.g. Teleport) along side of Heroes that do not feature any keywords.  I've not delved deeply enough to know for sure if the same filter is useful for the Extra Rules filter but it seems it should also fit well there.

Great work, I hope to use your site often!

**Comment by emfmesquita** [comment]
Good idea, I will take a look into that =)

thanks for the feedback

**Comment by emfmesquita** [comment]
Done:

![image](https://user-images.githubusercontent.com/8060611/132250680-720d5476-c981-4ec7-93ff-fcf0dcbbad9b.png)

It should be live now.
