### ISSUE TITLE
Incorrect icon on Wiccan's Sorcerous Illusions

### ISSUE THREAD

**Issue by Guli96** [emfmesquita/master-strike#21]
On one of Wiccan's commons, it says "Covert: You get +2 Attack"
Since the card doesn't have 0+ Attack on it, I decided to look up the full card and it seems like it should be +2 Recruit instead.
![kép](https://user-images.githubusercontent.com/97401347/148691919-b114b854-55d7-4705-b5d9-8c13a5d720fb.png)

**Comment by emfmesquita** [comment]
Indeed is wrong. Working on it. Thanks for the report! =)

**Comment by emfmesquita** [comment]
Fixed

![image](https://user-images.githubusercontent.com/8060611/148699697-04900612-1bcb-482c-bd2c-1c35da122c51.png)

Again, thank you very much for the report =)
