### ISSUE TITLE
Villainous Weapon

### ISSUE THREAD

**Issue by Organous** [emfmesquita/master-strike#24]
Villainous Weapon is currently not among the keywords for villains.

**Comment by emfmesquita** [comment]
Hello =)

Since "Villainous Weapon" is also a card subtype I mapped it separately. So it is in the "Extra Rules" filter. This is true for both masterminds and villains.

I will consider adding a separate rule and include it in the keyword filter too.

Thanks for the report. =)

**Comment by emfmesquita** [comment]
I finally added to the keyword filter too. Thanks for the feedback =)
