### ISSUE TITLE
Sakaaran Hivelings

### ISSUE THREAD

**Issue by olliekitkat** [emfmesquita/master-strike#38]
![image](https://user-images.githubusercontent.com/81947460/185990734-1897f5c4-1e01-4a52-8f3d-00cd1554b2e6.png)
![image](https://user-images.githubusercontent.com/81947460/185990856-fbb65f61-b28c-495c-aa10-84ba052a66b9.png)

Appears to be an error with the Sakaaran Hivelings. They do not appear in the drop down and do not appear to have a number associated with them.  Looks like it should be number 28. Probably just a typo :)

**Comment by emfmesquita** [comment]
You are 100% correct. Nice catch!! The card id was wrong (27 copied from the previous card) and it should be 28. I just fixed and deployed it should be ok now.
