### ISSUE TITLE
Deathbird Typo

### ISSUE THREAD

**Issue by olliekitkat** [emfmesquita/master-strike#52]
Deathbird's Token should be "Shi'ar Battlecruiser" instead of "Battleship"

![image](https://github.com/emfmesquita/master-strike/assets/81947460/8f86acbc-15b1-4410-891a-31f27acdc709)
![image](https://github.com/emfmesquita/master-strike/assets/81947460/096f61d0-714f-4665-8de0-bd00cea8de13)

**Comment by emfmesquita** [comment]
Sorry for the delay, you are correct. The fix should be live now. Thanks for reporting it =)
One interesting detail that I did not see, the names are different in the normal and epic versions of the card.
