### ISSUE TITLE
Psylocke - Telepathic Ninjutsu

### ISSUE THREAD

**Issue by ericapfelsensei** [emfmesquita/master-strike#55]
This card should be Instinct instead of Covert.

**Comment by emfmesquita** [comment]
You are correct once again, the fix should be online now. Thank you very much again for reporting it =)

**Comment by ericapfelsensei** [comment]
Thank you for all the work you put into the database. It's been
tremendously helpful for me while I work on designing a randomizer for my
group to use, and I was just helping to fix some very minor errors I
managed to spot along the way.

**Comment by emfmesquita** [comment]
You are welcome, I am glad I could help =)
