### ISSUE TITLE
Henchmen Dropdown Missing Sentinel Squad O*N*E*

### ISSUE THREAD

**Issue by Kylah15** [emfmesquita/master-strike#57]
![masterstrikebug](https://github.com/user-attachments/assets/0eeab4ac-0362-4717-843c-b8a8da46a8cc)

It shows up fine in the main list but when trying to add them manually to a grouping it is not available.

**Comment by emfmesquita** [comment]
Good catch!! It should be fixed now, thank you very much for reporting it =)
